### ISSUE TITLE
Detailed instructions on adding image in Xcode

### ISSUE THREAD

**Issue by morenoh149** [sconxu/react-native-checkbox#1]
Thanks for making this!
A link to http://guides.codepath.com/ios/Adding-Image-Assets or a similar gif for this project would be excellent.

**Comment by morenoh149** [comment]
https://facebook.github.io/react-native/docs/image.html#adding-static-resources-to-your-ios-app-using-images-xcassets

**Comment by sconxu** [comment]
Thanks for suggestion. I'll add the link.
