### ISSUE TITLE
Component styles should not override user styles

### ISSUE THREAD

**Issue by shssoichiro** [sconxu/react-native-checkbox#13]
Currently, on lines 49 and 58 of checkbox.js, you have code like this:

`<Text style={[this.props.labelStyle, styles.label]}>{this.props.label}</Text>`

The last item in a style array takes precedence. This means that the styles object built into the component always takes precedence over the user defined label styles. This, in turn, means that the user can never override the fontSize, lineHeight, or color of the label.

I'm not sure if this is intentional, but if it is, it seems like bad practice. It would be better to set `styles.label` as a default and let `this.props.labelStyle` override the built-in default styles.

**Comment by sconxu** [comment]
Not intentional. I will change that. Thanks for pointing it out!

**Comment by ExplodingCabbage** [comment]
This was fixed by https://github.com/sconxu/react-native-checkbox/commit/3673081b8f0ac8ba94360c5369373e40c3816c57 and should be closed.
