### ISSUE TITLE
Can't not change status

### ISSUE THREAD

**Issue by MinChanSike** [sconxu/react-native-checkbox#16]
CheckBox is just in initialize state. Can't not change it's status on press.

**Comment by cvongrim** [comment]
I am new to React Native so my implementation may be ugly, but you need to set a state and toggle it. This is what I did.

`/**
 * Test Form Component
 *
 */

'use strict';

var React = require('react-native');
var {
    View
    } = React;


var CheckBox = require('react-native-checkbox');

var TestForm = React.createClass({

    getInitialState: function () {
        return {
            checkBoxStatus: false,
        }
    },


    handleButtonPress: function() {
        this.setState({checkBoxStatus: !this.state.checkBoxStatus});
    },

    /**
     * Render the view
     * @returns {XML} the view to display
     */
    render: function () {
        return (
            <View>               
                <CheckBox
                    label='Checkbox Label'
                    checked={this.state.checkBoxStatus}
                    onChange={this.handleButtonPress}
                />
            </View>
        );
    }
});

module.exports = TestForm;`

**Comment by MinChanSike** [comment]
Thanks.
