### ISSUE TITLE
Checkbox won't change when touched

### ISSUE THREAD

**Issue by UKDeveloper99** [sconxu/react-native-checkbox#18]
Quite simple really, I've made a checkbox using the code in the README

When I touch the checkbox I get the log to tell me it's been touched but the tick doesn't appear. I can't toggle the checkbox on and off.

The device I'm using is Android 5.0

**Comment by UKDeveloper99** [comment]
Nevermind figured it out by looking through the closed issues. Would be good to add some notes about using a state variable to the readme

**Comment by gazpachu** [comment]
Correct. The example in the readme and the docs are not accurate. You have to change the 'checked' prop in order to make it change the status
