### ISSUE TITLE
Bottom of label text clipped on my phone

### ISSUE THREAD

**Issue by mark0978** [sconxu/react-native-checkbox#19]
If I don't change the label style to this, the bottom of the label is clipped on my nexus 6.  Thought this might have something to do with the accessibility settings on my phone, but even when I change it from large font back to normal font the clipping continues.  And it isn't even the descenders that are getting clipped.
```js
  label: {
    fontSize: 14,
    lineHeight: 15,
    color: 'grey',
  }
```
When you change the label to one that has a descender, you end up having to lower the font height to 12.  Or, you can fix it all by removing the lineHeight style altogether and then it just works.

**Comment by sconxu** [comment]
Should be fixed in the latest version. Thanks for suggestions.
