### ISSUE TITLE
can't find variable Checkbox

### ISSUE THREAD

**Issue by susylPearl** [sconxu/react-native-checkbox#25]
when i implement it in my android application , it shows error as can't find variable Checkbox.
I have installed it through npm install react-native-checkbox --save and in my node modules folder this exist and aslo exist in package.json. But shows error whats the problem? please suggest me.

**Comment by luisfuertes** [comment]
Can you post a example of your code?

You have imported Checkbox on top? 
`import Checkbox from 'react-native-checkbox'`
