### ISSUE TITLE
Requiring unknow module "./cb_disabled.png"

### ISSUE THREAD

**Issue by KGALLET** [sconxu/react-native-checkbox#29]
Hi,

I'm using "react-native-checkbox": "^1.0.12" on iOS real device. (iPhone 6S)

![13324113_1192307630814415_1896998830_o](https://cloud.githubusercontent.com/assets/14168629/15750894/5b3e5a18-28e8-11e6-8b38-4bf701942528.jpg)

**Comment by dbecker215** [comment]
I'm having the same issue.

**Comment by adnanhemani** [comment]
Same issue here too. Running on an iOS Simulator though.

**Comment by satyagupta** [comment]
Same issue here too. Need a fix at the earliest.

**Comment by sconxu** [comment]
Should be fine now.
