### ISSUE TITLE
Detail sample usage with flux

### ISSUE THREAD

**Issue by morenoh149** [sconxu/react-native-checkbox#3]
In a project we are utilizing multiple instances of this component in a view along with flux. We have something like
```javascript
<CheckBox
  label=''
  onChange={this.props.onPress}
  checked={this.props.completed}
/>
```
where the `onPress` handler is a flux action creator
```javascript
onToggleTask={(taskId) =>
  dispatch(toggleTask(taskId))
}
```
This was causing a weird issue because the onChange handler would mutate the passed in prop (`this.props.completed`) but this component also mutates it's own state at https://github.com/sconxu/react-native-checkbox/blob/master/checkbox.js#L39 essentially we would trigger two mutations of the checked state upon click. We ended up adding this dependency under version control and change it's internal behavior to use the passed in prop over it's local state.

How would you prescribe an end-user use this component within a flux app?

**Comment by morenoh149** [comment]
I see here https://github.com/sconxu/react-native-checkbox/blob/master/checkbox.js#L42 the callback is invoked with the checkbox's updated state. So documenting this behavior similar to [TextInput#onChangeText](https://facebook.github.io/react-native/docs/textinput.html#onchangetext) would be helpful.

**Comment by sconxu** [comment]
Thanks for pointing this out. I haven't used flux yet, so I don't know how it affects the checkbox component. I will take a look and come back.

**Comment by morenoh149** [comment]
I think this module needs to expose an `onClick` prop. This handler will execute when the checkbox is clicked. Doesn't necessarily mutate the checked state as the state may be passed in via props to `checked={}`
