### ISSUE TITLE
any example code for "how to use"

### ISSUE THREAD

**Issue by manupytwn** [sconxu/react-native-checkbox#33]
Hi!

I was checking the module, it seems to work but the checkbox doesn't change after click on it. I think that I need to init the vale for "checked" to "true" after click but I can't see the way.

Any example of code that might help? 

Thks!

**Comment by bogdancarmanus** [comment]
Hi, 
There is a handler for the onChange event where you can change the checked property outside the component.

**Comment by manupytwn** [comment]
Thank you!

Finally it is working. I've attached the code to help others.

`
/**
 * Sample for "react-native-checkbox"
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import CheckBox from 'react-native-checkbox';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});

var MyCheckTest = React.createClass({
  getInitialState() {
    return {
      checkedButton: false,
    };
  },
  render() {
    return (
      <View style={styles.container}>
        <CheckBox
          label="YEAH"
          checked={this.state.checkedButton}
          onChange={(checked) => this._toggle(checked)}
        />
      </View>
    );
  },

  _toggle: function(value) {
    console.log('I am checked', value);
    this.setState({ checkedButton: value });
  },

});

AppRegistry.registerComponent('MyCheckTest', () => MyCheckTest);
`
