### ISSUE TITLE
Checkbox not changing the state.

### ISSUE THREAD

**Issue by flexdhana** [sconxu/react-native-checkbox#35]
I have successfully included with my project, but checkbox not changing the state dynamically on click. But its changing when i change the component properties "checked={true} (or) checked={false}"

any suggestion?

**Comment by bogdancarmanus** [comment]
This is the way it works. The state of the checkbox must be changed outside the component using onChange event.

**Comment by flexdhana** [comment]
@bogdancarmanus , thanks, i made it work by following change..

constructor(props){
    super(props);
    this.state = {
            checked: false
        };
  }

checkBoxChanged()
{
     this.state.checked?this.setState({checked: false}):this.setState({checked: true});
}

<CheckBox label='Label'
                    checked={this.state.checked}
                     onChange={this.checkBoxChanged.bind(this)}
/>
