### ISSUE TITLE
how to hide the label text

### ISSUE THREAD

**Issue by aiuluna** [sconxu/react-native-checkbox#38]
i don't want the label text,how to hide it

**Comment by bogdancarmanus** [comment]
Try not to provide any label to the component

**Comment by aiuluna** [comment]
<CheckBox
          checked={this.state.checked}
          checkboxStyle={{width:14,height:14}}
          onChange={(checked) => this.state.checked?this.setState({checked:false}):this.setState({checked:true})}
          />


use this,show the default text  'label'

**Comment by aiuluna** [comment]
label={''}
use this ,thanks
