### ISSUE TITLE
Toggle check onPress

### ISSUE THREAD

**Issue by edencakir** [sconxu/react-native-checkbox#39]
What about toggling by default and use a callback on onChange method, or something similar? Nothing happens when onPressed

**Comment by Jaafar-abusair** [comment]
+1

**Comment by sconxu** [comment]
The latest version supports now both scenarios. It toggles by default and you get the changed value on onChange callback. If you want to control the checkbox from outside the component than you will need to manage the state outside using onChange callback and send it to component through the checked property.
