### ISSUE TITLE
simple example doesn't work

### ISSUE THREAD

**Issue by jcollum** [sconxu/react-native-checkbox#40]
```
import React, {Component} from 'react';
import {View, Text} from 'react-native';
import CheckBox from 'react-native-checkbox';

export default class PageTwo extends Component {

  render() {
    let save = false;

    return (
      <View style={{margin:80}}>
        <Text>Checkbox</Text>
        <CheckBox label='Save this!' checked={save} onChange={(checked) => {
          save = checked;
          return true;
        }
        }/>
      </View>
    )
  }
}
```

When rendered, clicking the text of the label or the checkbox itself will not toggle the checked state of the checkbox. Sorry if I'm doing something wrong but this seemed to library-specific to put on StackOverflow.

**Comment by andrew-icf** [comment]
+1 I keep getting this error
 Unexpected character '�' (1:0)

**Comment by jcollum** [comment]
@andrew-icf  I ended up using this: `import {MKCheckbox} from 'react-native-material-kit';` Works pretty well. Make sure you restart your React-Packager after installing.

**Comment by andrew-icf** [comment]
Awesome! Thank you 

    On Tuesday, October 11, 2016 8:36 PM, Justin Collum <notifications@github.com> wrote:
 

 @andrew-icf I ended up using this: import {MKCheckbox} from 'react-native-material-kit'; Works pretty well. Make sure you restart your React-Packager after installing. —
