### ISSUE TITLE
Initial value will break check behavior

### ISSUE THREAD

**Issue by joeyzhao0113** [sconxu/react-native-checkbox#54]
I am using below code to set the initial value to `true` on check box.
But whatever I click on the checkbox, it always show selected. I can't unselect the checkbox unless I remove the initial value `checked={true}`.

```
<CheckBox
            labelStyle={{fontSize: FontSize.small}}
            label='title'
            checked={true}
            onChange={(checked) => {
              this.setState({state: !checked})
            }}
          />
```

**Comment by seigel** [comment]
Interesting. I also see that the value coming back is inverted from what you'd expect, and you seem to have done the same as well with your ```!checked```
I can confirm the same behaviour

**Comment by seigel** [comment]
Seems to work if you manage the external variable properly.

**Comment by joeyzhao0113** [comment]
the document says `checked` is initial value so I didn't use it correctly.
