### ISSUE TITLE
Feature Request: allow icons for uncheckedImage and checkedImage

### ISSUE THREAD

**Issue by abeaclark** [sconxu/react-native-checkbox#62]
Thanks for this component.

Many people use icon libraries like [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons)

The current api requires an image file. It would be great if it could also accept another element (like an icon) to use as the toggle.

Let me know if you would like help with this feature.

Thanks!

**Comment by sconxu** [comment]
You're welcome! Would be nice to have that.
Please create a new pull request.
