### ISSUE TITLE
this box is checked, but the check vulue is 'false'?

### ISSUE THREAD

**Issue by weinengjian** [sconxu/react-native-checkbox#63]
![que](https://user-images.githubusercontent.com/23124071/27984161-cb173202-6400-11e7-900b-ace0e69e586d.PNG)

`onChange={(checked) => console.log('I am checked', checked)}`

**Comment by weinengjian** [comment]
and when it not checked, the value returned is true

**Comment by angelofrancisco** [comment]
@weinengjian I'm having the same problem as well. I have temporarily fixed it by returning `!checked` instead until the library is fixed. It seems like the author is checking the previous state of the button or is returning the wrong boolean.
