### ISSUE TITLE
SyntaxError: /Users/[…]/react-native-checkbox/cb_enabled.png

### ISSUE THREAD

**Issue by cesargdm** [sconxu/react-native-checkbox#67]
<img width="762" alt="screen shot 2017-08-11 at 2 53 07 pm" src="https://user-images.githubusercontent.com/10179494/29229598-e02774a4-7ea4-11e7-83c5-3b70710d3fc3.png">

Using macOS, react-native 0.45.1, react 16.0.0-alpha.12

**Comment by cesargdm** [comment]
Had to reinstall all packages, no error now

**Comment by kabirvirji** [comment]
@cesargdm had the same error and then re-installed & installed and it works

**Comment by crazy4groovy** [comment]
I'm seeing this error, tried to clean node_modules folder but still didn't help:

```
    C:\dev\projects\consumer\node_modules\react-native-checkbox\cb_enabled.png:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){�PNG
                                                                                             ^
    
    SyntaxError: Invalid or unexpected token
```

Windows 10
