### ISSUE TITLE
just init value is used to select picture

### ISSUE THREAD

**Issue by joterr** [sconxu/react-native-checkbox#81]
Maybe the init value is used to select the picture on every change - so the tick picture is always visible or hidden depending on the init value.

https://github.com/sconxu/react-native-checkbox/blob/2f819cea3b4d2519236f47a7547d74ed482e77ff/checkbox.js#L62-L66

**Comment by baharb** [comment]
I changed the OnChange function, and now it works well.
Just use the state for check box value and change the OnChange function like this:
http://zcontrol.ir/fix-react-native-checkbox-problem/
