### ISSUE TITLE
Checked state doesn´t change?!

### ISSUE THREAD

**Issue by BigPun86** [sconxu/react-native-checkbox#9]
Hey there,

i tried this component, but unfortunately whatever i do, it never changes the state when i click the checkbox...Here´s my code:

Render Method of Checkbox, where i just changed the image sources:

     render() {
        var source = require ('image!ic_uncheck_white'); // whitebox - placeholder

        if (this.props.checked) {
            source = require ('image!ic_check_black_24dp');
        }   

render Method where i use the Checkbox Component:

                        <View style={styles.row}>
                            <CheckBox
                                style={{flex:1}}
                                label={PREMIUM_ITEMS[2]}
                                checked={this.props.checkedGroups}
                                onChange={(checked) => this._pressRowListener(checked)}
                            />
                        </View>
                        <View style={styles.separator}/>

 _pressRowListener: function ( checked ) {

        ToastAndroid.show('checked is ' + checked, ToastAndroid.SHORT);

    }

**Comment by sconxu** [comment]
Hi, 
You need to have checkedGroups as state instead of prop and change it inside _pressRowListener. You decide the value of the checked property outside the component.

**Comment by BigPun86** [comment]
Upps! I missed that, thanks a lot
